from flask import Flask, render_template, request, jsonify
from model_utils import predict_url, predict_email, predict_smart, MultiHeadSelfAttention
from model_utils import predict_url, predict_email, predict_smart, MultiHeadSelfAttention
from crawler import analyze_webpage
from domain_info import get_domain_info
from flask_cors import CORS
import tensorflow as tf
import joblib
import joblib
import os
import datetime
import uuid
from fpdf import FPDF

# Define base directory for absolute paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(BASE_DIR, 'models')

app = Flask(__name__)
CORS(app)  # Enable CORS for Chrome Extension

# Global variables for both models
url_model = None
email_model = None
url_vectorizer = None
email_vectorizer = None
model_info = None
email_model_info = None

# Scan History Storage
scan_history = []

class PDFReport(FPDF):
    def clean_text(self, text):
        """Sanitize text for Latin-1 encoding (replace unsupported chars)"""
        return str(text).encode('latin-1', 'replace').decode('latin-1')

    def header(self):
        # Logo or Title styling
        self.set_font('Arial', 'B', 20)
        self.set_text_color(33, 37, 41)  # Dark Gray
        self.cell(0, 10, 'Phishing Detection Security Report', 0, 1, 'L')
        
        # Decorative Line
        self.set_line_width(0.5)
        self.set_draw_color(0, 217, 255) # Cyan Primary
        self.line(10, 22, 200, 22)
        self.ln(15)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128) # Gray
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Phishing Detection System', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 14)
        self.set_fill_color(24, 29, 41) # Dark Blue/Black Background
        self.set_text_color(0, 217, 255) # Cyan Text
        self.cell(0, 10, f"  {title}", 0, 1, 'L', fill=True)
        self.ln(4)

    def section_kv(self, key, value, new_line=True):
        self.set_font('Arial', 'B', 10)
        self.set_text_color(50, 50, 50)
        self.cell(50, 6, f"{key}:", 0, 0)
        self.set_font('Arial', '', 10)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 6, self.clean_text(str(value)))
        if new_line:
            self.ln(2)

def load_model_components():
    """Load all model components at startup"""
    global url_model, email_model, url_vectorizer, email_vectorizer, model_info, email_model_info
    
    try:
        models_loaded = 0
        
        # Load URL model
        phishing_model_path = os.path.join(MODEL_DIR, 'phishing_model.h5')
        if os.path.exists(phishing_model_path):
            print("🔄 Loading URL model...")
            url_model = tf.keras.models.load_model(phishing_model_path, custom_objects={
                'MultiHeadSelfAttention': MultiHeadSelfAttention
            })
            url_vectorizer = joblib.load(os.path.join(MODEL_DIR, 'vectorizer.pkl'))
            
            model_info_path = os.path.join(MODEL_DIR, 'model_info.pkl')
            if os.path.exists(model_info_path):
                model_info = joblib.load(model_info_path)
            
            print("✅ URL model loaded successfully!")
            models_loaded += 1
        
        # Load Email model
        email_model_path = os.path.join(MODEL_DIR, 'email_model.h5')
        if os.path.exists(email_model_path):
            print("🔄 Loading Email model...")
            email_model = tf.keras.models.load_model(email_model_path, custom_objects={
                'MultiHeadSelfAttention': MultiHeadSelfAttention
            })
            email_vectorizer = joblib.load(os.path.join(MODEL_DIR, 'email_vectorizer.pkl'))
            
            email_model_info_path = os.path.join(MODEL_DIR, 'email_model_info.pkl')
            if os.path.exists(email_model_info_path):
                email_model_info = joblib.load(email_model_info_path)
            
            print("✅ Email model loaded successfully!")
            models_loaded += 1
        
        if models_loaded == 0:
            print("❌ No models found! Please run 'python train_model.py' first.")
            return False
         
        print(f"✅ {models_loaded}/2 models loaded successfully!")
        return True
        
    except Exception as e:
        print(f"❌ Error loading models: {e}")
        return False

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json()
        input_text = data.get('input', '').strip()
        input_type = data.get('type', 'auto')  # 'url', 'email', or 'auto'
        
        if not input_text:
            return jsonify({'error': 'Input is required'}), 400
            
        # 1. Determine Category (URL or Email)
        from model_utils import detect_input_type
        category = input_type.upper()
        if category == 'AUTO':
            category = detect_input_type(input_text).upper()
            
        print(f"🔍 Analyzing Input Category: {category}")

        # --- FLOW A: ADVANCED URL ANALYSIS (Visit/Crawler + WHOIS + AI) ---
        if category == 'URL':
            if url_model is None:
                return jsonify({'error': 'URL model not loaded'}), 500
            
            # STEP 1: AI Model Prediction
            ai_result = predict_smart(
                input_text, 
                url_model=url_model, 
                url_vectorizer=url_vectorizer,
                email_model=email_model,
                email_vectorizer=email_vectorizer
            )
            model_score = ai_result['confidence']
            
            # STEP 2: Domain WHOIS Intelligence
            try:
                domain_data = get_domain_info(input_text)
                domain_score = domain_data.get('risk_score', 0)
            except Exception as e:
                print(f"⚠️ WHOIS failed: {e}")
                domain_data = {}
                domain_score = 0
            
            # STEP 3: Webpage Behavior Crawler (The "Visit" component)
            try:
                print(f"🕷️ Running Crawler Analysis (SITE VISIT) on: {input_text}")
                # Ensure URL has scheme for Selenium
                crawler_url = input_text
                if not crawler_url.startswith(('http://', 'https://')):
                    crawler_url = 'http://' + crawler_url
                    
                behavior_result = analyze_webpage(crawler_url)
                behavior_score = behavior_result.get('behavior_score', 0)
                behavior_flags = behavior_result.get('flags', [])
                legitimacy_signals = behavior_result.get('legitimacy_signals', [])
            except Exception as e:
                print(f"⚠️ Crawler failed: {e}")
                behavior_score = 0
                behavior_flags = [f"Crawler check failed: {str(e)}"]
                legitimacy_signals = []
            
            # --- FINAL HYBRID SCORING ---
            # Standard weights: 60% model + 20% domain + 20% behavior
            weighted_score = (model_score * 0.6) + (domain_score * 0.2) + (behavior_score * 0.2)
            final_score = weighted_score
            
            # LEGITIMACY OVERRIDE: If the visit found strong company signals, lower the risk.
            if len(legitimacy_signals) >= 3:
                print(f"🛡️ Strong Legitimacy Signals found by Crawler. Lowering risk for URL.")
                final_score = min(weighted_score, 25) 
            elif len(legitimacy_signals) >= 2:
                final_score = min(weighted_score, 45) # Max "Suspicious"
                
            # If AI is highly confident AND no legitimacy signals were found, lean towards AI
            if model_score > 85 and len(legitimacy_signals) == 0:
                final_score = max(weighted_score, model_score * 0.9)
                
            # --- TRUSTED DOMAIN OVERRIDE ---
            TRUSTED_DOMAINS = {
                'openai.com', 'chatgpt.com', 'google.com', 'youtube.com', 'facebook.com', 
                'amazon.com', 'wikipedia.org', 'twitter.com', 'instagram.com', 'linkedin.com', 
                'netflix.com', 'microsoft.com', 'apple.com', 'github.com', 'stackoverflow.com', 
                'reddit.com', 'yahoo.com', 'bing.com', 'twitch.tv', 'whatsapp.com', 
                'adobe.com', 'salesforce.com', 'zoom.us', 'outlook.com', 'live.com',
                'nytimes.com', 'cnn.com', 'bbc.com', 'wsj.com', 'forbes.com', 'bloomberg.com',
                'medium.com', 'quora.com', 'dropbox.com', 'paypal.com', 'shopify.com',
                'phoneticedu.com'
            }
            
            # Clean domain extraction for whitelist check
            try:
                clean_url = input_text.replace('https://', '').replace('http://', '')
                domain_part = clean_url.split('/')[0]
                if domain_part.startswith('www.'): domain_part = domain_part[4:]
                if ':' in domain_part: domain_part = domain_part.split(':')[0]
            except:
                domain_part = ""

            is_trusted_domain = domain_part.lower() in TRUSTED_DOMAINS
            trusted_tlds = ('.ac.in', '.edu', '.gov', '.mil', '.org.in', '.nic.in')
            is_trusted_tld = domain_part.lower().endswith(trusted_tlds)
            
            suspicious_words_found = ai_result.get('suspicious_words', [])
            has_critical_keywords = any(w in suspicious_words_found for w in ['verify', 'account', 'login', 'update', 'payment'])
            
            if is_trusted_domain or (is_trusted_tld and not has_critical_keywords):
                 print(f"🛡️ Trusted Source detected: {domain_part}. Lowering risk.")
                 final_score = min(final_score, 15) 
                 recommendation = "Safe - Trusted / Verified Source"
            
            final_score = round(min(max(final_score, 0), 100), 2)
            
            # --- VERDICT DETERMINATION ---
            if final_score > 70:
                recommendation = "DO NOT VISIT - Highly Dangerous"
                prediction_label = "Phishing"
            elif final_score >= 40:
                recommendation = "Suspicious - Proceed Carefully"
                prediction_label = "Suspicious"
            else:
                recommendation = "Safe to Visit"
                prediction_label = "Legitimate"
            
            result = {
                'prediction': prediction_label,
                'confidence': final_score,
                'recommendation': recommendation,
                'scores': {
                    'ai_model': model_score,
                    'domain_risk': domain_score,
                    'behavior_risk': behavior_score,
                    'transformer': ai_result['scores'].get('transformer', 0),
                    'rule_based': ai_result['scores'].get('rule_based', 0),
                    'final': final_score
                },
                'domain_info': {
                    'creation_date': domain_data.get('creation_date', 'Unknown'),
                    'domain_age_days': domain_data.get('domain_age_days', 0),
                    'registrar': domain_data.get('registrar', 'Unknown')
                },
                'behavior_findings': behavior_flags,
                'legitimacy_signals': legitimacy_signals,
                'website_purpose': behavior_result.get('website_purpose', 'N/A'),
                'website_category': behavior_result.get('website_category', 'General'),
                'design_intent': behavior_result.get('design_intent', 'N/A'),
                'suspicious_words': list(set(ai_result.get('suspicious_words', []) + behavior_result.get('suspicious_words', []))),
                'input': input_text,
                'type': 'URL',
                'status': 'success'
            }

        # --- FLOW B: EMAIL ANALYSIS ---
        elif category == 'EMAIL':
            if email_model is None:
                return jsonify({'error': 'Email model not loaded'}), 500
            result = predict_email(input_text, model=email_model, vectorizer=email_vectorizer)
            recommendation = "Legitimate Email" if result['prediction'] == 'Legitimate' else "Potential Phishing Email"
            result['recommendation'] = recommendation

        else:
            return jsonify({'error': f'Category {category} not supported'}), 400

        
        # Generate unique scan ID and timestamp
        scan_id = str(uuid.uuid4())
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Add scan metadata to result
        result['scan_id'] = scan_id
        result['timestamp'] = timestamp
        
        # Store in history
        history_entry = {
            'id': scan_id,
            'input': input_text,
            'type': result.get('type', 'Unknown'),
            'prediction': result.get('prediction', 'Unknown'),
            'confidence': result.get('confidence', 0),
            'scores': result.get('scores', {}),
            'suspicious_words': result.get('suspicious_words', []),
            'domain_info': result.get('domain_info', {}),
            'recommendation': result.get('recommendation', 'N/A'),
            'behavior_findings': result.get('behavior_findings', []),
            'legitimacy_signals': result.get('legitimacy_signals', []),
            'website_purpose': result.get('website_purpose', 'N/A'),
            'website_category': result.get('website_category', 'General'),
            'design_intent': result.get('design_intent', 'N/A'),
            'timestamp': timestamp,
            'status': result.get('status', 'complete')
        }
        scan_history.insert(0, history_entry) # Add to beginning of list
        
        # Keep only last 50 entries
        if len(scan_history) > 50:
            scan_history.pop()
            
        return jsonify(result)
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/history')
def get_history():
    """Get scan history"""
    return jsonify(scan_history)



@app.route('/download_report/<scan_id>')
def download_report(scan_id):
    """Generate and download a dynamic PDF report for a specific scan"""
    scan_data = next((item for item in scan_history if item['id'] == scan_id), None)
    
    if not scan_data:
        return jsonify({'error': 'Scan not found'}), 404
        
    try:
        # Create PDF
        pdf = PDFReport()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        
        # --- METADATA ---
        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"Report ID: {scan_data['id']}", 0, 1, 'L')
        pdf.cell(0, 5, f"Date: {scan_data['timestamp']}", 0, 1, 'L')
        pdf.ln(5)

        # --- EXECUTIVE SUMMARY ---
        pdf.chapter_title("Executive Summary")
        
        # Verdict
        prediction = scan_data.get('prediction', 'Unknown')
        confidence = scan_data.get('confidence', 0)
        
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(40, 8, "Verdict:", 0, 0)
        
        if prediction == "Phishing":
            pdf.set_text_color(220, 53, 69) # Red
        elif prediction == "Suspicious":
             pdf.set_text_color(255, 193, 7) # Orange
        else:
            pdf.set_text_color(40, 167, 69) # Green
            
        pdf.cell(0, 8, prediction.upper(), 0, 1)
        pdf.set_text_color(0, 0, 0) # Reset
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(40, 6, "Confidence:", 0, 0)
        pdf.cell(0, 6, f"{confidence}%", 0, 1)
        pdf.cell(40, 6, "Recommendation:", 0, 0)
        pdf.multi_cell(0, 6, pdf.clean_text(scan_data.get('recommendation', 'N/A')))
        pdf.ln(4)
        
        # --- ANALYSIS ---
        pdf.chapter_title("Input Analysis")
        pdf.section_kv("Analyzed Input", scan_data.get('input', 'N/A'))
        pdf.section_kv("Type", scan_data.get('type', 'Unknown').upper())
        
        dom_info = scan_data.get('domain_info', {})
        if dom_info and scan_data.get('type') == 'URL':
            pdf.ln(2)
            pdf.set_font('Arial', 'B', 10)
            pdf.cell(0, 6, "Domain Intelligence:", 0, 1)
            pdf.set_font('Arial', '', 10)
            pdf.section_kv("  - Establishment", dom_info.get('creation_date', 'Unknown'), new_line=False)
            pdf.section_kv("  - Age", f"{dom_info.get('domain_age_days', 0)} days", new_line=False)
            pdf.section_kv("  - Registrar", dom_info.get('registrar', 'Unknown'), new_line=True)

        pdf.ln(2)
        
        # --- SCORING BREAKDOWN ---
        pdf.chapter_title("Risk Assessment Scores")
        scores = scan_data.get('scores', {})
        
        def draw_score_bar(label, score):
            pdf.set_font('Arial', '', 10)
            pdf.cell(60, 6, label, 0, 0)
            
            # Draw bar background
            x = pdf.get_x()
            y = pdf.get_y()
            pdf.set_fill_color(230, 230, 230)
            pdf.rect(x, y+1, 80, 4, 'F')
            
            # Draw actual score
            if score > 70: pdf.set_fill_color(220, 53, 69)
            elif score > 40: pdf.set_fill_color(255, 193, 7)
            else: pdf.set_fill_color(40, 167, 69)
            
            bar_width = (score / 100) * 80
            if bar_width > 0:
                pdf.rect(x, y+1, bar_width, 4, 'F')
                
            pdf.set_x(x + 85)
            pdf.cell(20, 6, f"{score}/100", 0, 1)

        draw_score_bar("AI Transformer Model", scores.get('transformer', 0))
        draw_score_bar("Heuristic Rules", scores.get('rule_based', 0))
        draw_score_bar("Domain Risk Profile", scores.get('domain_risk', 0))
        draw_score_bar("Web Behavior Risk", scores.get('behavior_risk', 0))
        
        pdf.ln(2)
        pdf.set_font('Arial', 'B', 10)
        
        # Consistent with Frontend: Show Safety Score if Legitimate
        final_score = scores.get('final', 0)
        if prediction == "Legitimate":
            display_label = "FINAL SAFETY SCORE:"
            display_value = round(100 - final_score, 2)
        else:
            display_label = "FINAL RISK SCORE:"
            display_value = final_score
            
        pdf.cell(60, 8, display_label, 0, 0)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, f"{display_value}/100", 0, 1)
        pdf.ln(4)

        # --- WEBSITE PROFILE ---
        if scan_data.get('type') == 'URL':
            pdf.chapter_title("Website Profile & Purpose Analysis")
            pdf.set_font('Arial', 'B', 10)
            pdf.set_text_color(0, 102, 204) # Blue
            pdf.cell(40, 6, "Category:", 0, 0)
            pdf.set_font('Arial', '', 10)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 6, scan_data.get('website_category', 'General'), 0, 1)
            
            pdf.set_font('Arial', 'B', 10)
            pdf.set_text_color(102, 0, 204) # Purple
            pdf.cell(40, 6, "Design Intent:", 0, 0)
            pdf.set_font('Arial', '', 10)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 6, scan_data.get('design_intent', 'N/A'), 0, 1)
            
            # Visual Trust calculation
            signals_count = len(scan_data.get('legitimacy_signals', []))
            trust_level = "High" if signals_count >= 3 else "Medium" if signals_count >= 1 else "Low/New"
            
            pdf.set_font('Arial', 'B', 10)
            pdf.set_text_color(40, 167, 69) # Green
            pdf.cell(40, 6, "Visual Trust:", 0, 0)
            pdf.set_font('Arial', '', 10)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 6, trust_level, 0, 1)

            pdf.ln(2)
            pdf.set_font('Arial', 'B', 10)
            pdf.cell(0, 6, "Site Utility & Purpose Summary:", 0, 1)
            pdf.set_font('Arial', '', 10)
            purpose = scan_data.get('website_purpose', 'N/A')
            # Clean summary from markdown bold stars
            purpose = purpose.replace("**", "")
            pdf.multi_cell(0, 6, pdf.clean_text(purpose))
            pdf.ln(4)

        # --- FINDINGS ---
        pdf.chapter_title("Detailed Findings")
        
        # Keywords
        words = scan_data.get('suspicious_words', [])
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(0, 6, "Suspicious Keywords Detected:", 0, 1)
        pdf.set_font('Arial', '', 10)
        if words:
            pdf.multi_cell(0, 6, pdf.clean_text(", ".join(words)))
        else:
            pdf.cell(0, 6, "None detected.", 0, 1)
        pdf.ln(2)
        
        # Behavior
        findings = scan_data.get('behavior_findings', [])
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(0, 6, "Behavioral Anomalies:", 0, 1)
        pdf.set_font('Arial', '', 10)
        if findings:
            for flag in findings:
                pdf.cell(5, 6, "-", 0, 0)
                pdf.multi_cell(0, 6, pdf.clean_text(str(flag)))
        else:
            pdf.cell(0, 6, "No behavioral anomalies detected/Crawler skipped.", 0, 1)
        pdf.ln(2)

        # Legitimacy Signals
        legitimacy = scan_data.get('legitimacy_signals', [])
        if legitimacy:
            pdf.set_font('Arial', 'B', 10)
            pdf.set_text_color(40, 167, 69) # Green
            pdf.cell(0, 6, "Verified Legitimacy Signals (Positive Markers):", 0, 1)
            pdf.set_font('Arial', '', 10)
            pdf.set_text_color(0, 0, 0) # Reset
            for signal in legitimacy:
                pdf.cell(5, 6, "+", 0, 0)
                pdf.multi_cell(0, 6, pdf.clean_text(str(signal)))
            pdf.ln(2)
        # Save
        folder = os.path.join(BASE_DIR, 'reports')
        os.makedirs(folder, exist_ok=True)
        filename = f"security_report_{scan_id}.pdf"
        filepath = os.path.join(folder, filename)
        pdf.output(filepath)
        
        from flask import send_file
        return send_file(filepath, as_attachment=True, download_name=filename)
        
    except Exception as e:
        print(f"PDF Generation Error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/model-info')
def get_model_info():
    """Get model performance information"""
    try:
        info = {
            'loaded': True,
            'models': {}
        }
        
        if model_info:
            info['models']['url'] = model_info
        
        if email_model_info:
            info['models']['email'] = email_model_info
        
        return jsonify(info)
    except Exception as e:
        return jsonify({'loaded': False, 'error': str(e)})

@app.route('/status')
def status():
    """Check if models are loaded and ready"""
    """Check if models are loaded and ready"""
    url_ready = url_model is not None and os.path.exists(os.path.join(MODEL_DIR, 'phishing_model.h5'))
    email_ready = email_model is not None and os.path.exists(os.path.join(MODEL_DIR, 'email_model.h5'))
    
    return jsonify({
        'url_model_loaded': url_ready,
        'email_model_loaded': email_ready,
        'models_available': {
            'url': url_ready,
            'email': email_ready
        },
        'ready': url_ready or email_ready  # Ready if at least one model is loaded
    })

@app.route('/api/check_url', methods=['GET'])
def check_url_api():
    """API Endpoint for Chrome Extension"""
    url = request.args.get('url')
    if not url:
        return jsonify({'error': 'URL is required'}), 400
        
    try:
        # Use predict_smart but force URL type if possible or just use existing logic
        # For simplicity, we call predict_smart which calls detect_input_type
        # Since it's a URL parameter, it should be detected as URL
        
        # Note: We skip the heavy crawler for the API to keep it fast for the extension, 
        # OR we can include it. The user asked for "Real-Time", but crawler is slow (Selenium).
        # The user instruction was: "Call predict_smart(url)". It didn't explicitly say "Call analyze_webpage".
        # However, predict_smart in app.py now calls analyze_webpage via the '/predict' route logic? 
        # No, predict_smart is in model_utils.py and does NOT call app.py logic.
        # Implication: The API will return the fast AI score (predict_smart) without the slow crawler.
        # This is better for a Chrome Extension user experience (speed).
        
        result = predict_smart(
            url, 
            url_model=url_model, 
            url_vectorizer=url_vectorizer,
            email_model=email_model,
            email_vectorizer=email_vectorizer
        )
        
        return jsonify({
            "url": url,
            "prediction": result['prediction'],
            "confidence": result['confidence']
        })
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    print("🚀 Starting Multi-Modal Phishing Detection System...")
    print("🔍 Supports both URL and Email analysis")
    
    # Load model components at startup
    if not load_model_components():
        print("\n⚠️  Models not found or failed to load!")
        print("Please run the following command first:")
        print("python train_model.py")
        print("\nThen restart the application with:")
        print("python app.py")
        print("\n" + "="*50)
        print("Starting server anyway (you can train models later)...")
    else:
        print("🎉 Models loaded successfully!")
    
    print("🌐 Starting Flask server...")
    print("📱 Open http://localhost:5000 in your browser")
    print("="*50)
    
    app.run(debug=True, port=5000)
